CREATE TABLE captains_log (
	id SERIAL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	article TEXT NOT NULL
)

CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	username VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL
);

CREATE TABLE "session" (
  "sid" varchar NOT NULL COLLATE "default",
	"sess" json NOT NULL,
	"expire" timestamp(6) NOT NULL
)
WITH (OIDS=FALSE);
ALTER TABLE "session" ADD CONSTRAINT "session_pkey" PRIMARY KEY ("sid") NOT DEFERRABLE INITIALLY IMMEDIATE;

CREATE TABLE html (
	id SERIAL PRIMARY KEY,
	field_id VARCHAR(255) NOT NULL,
	text TEXT NOT NULL,
	page VARCHAR(255) NOT NULL,
	type VARCHAR(255) NOT NULL
);